[window]
opacity=0.93
padding.x = 5
padding.y = 5
dynamic_padding = true

[font]
size=10

[font.normal]
family="Terminus"
style="Regular"

[font.bold]
family="Terminus"
style="Regular"

[font.italic]
family="Terminus"
style="Regular"

[font.bold_italic]
family="Terminus"
style="Regular"
